version: '3.8'
services:

  api:
    container_name: api-container
    restart: always
    build : ./backend/app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  frontend:
    container_name: frontend-container
    restart: always
    build : ./frontend
    ports:
      - "8020:8080"
    depends_on:
      - api
  mongo:
    container_name: mongo-backend
    image: mongo
    expose :
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - apiDB:/data/db
volumes:
  apiDB:
