const mongoose = require("mongoose");

const agentSchema = mongoose.Schema({
  first_name: "string",
  last_name: "string",
  email: "string",
  affiliation: "string",
  country: "string",
  bio: "string",
  artifact_type: "string",
  artifact_name: "string",
  key_phrase_1: "string",
  key_phrase_2: "string",
  key_phrase_3: "string",
  key_phrase_4: "string",
  key_phrase_5: "string",
  csv_url: "string",
  source_code_availability: "string",
  previous_version_availability: "string",
  previous_version_urls: "string",
  licence: "string",
  bug_history_availability: "string",
  framework_used: "string",
  framework_used_url: "string",
  framework_used_version: "string",
  apps_developed: "string",
  documentation_availability: "string",
  technical_assistance_availability: "string",
  additional_tools_needed: "string",
  user_testing_status: "string",
  user_testing_url: "string",
  software_engineering_methodology: "string",
  technical_paper1: "string",
  technical_paper2: "string",
  code_reuse_licence: "string",
  comments: "string",
});

module.exports = mongoose.model("Agent", agentSchema);
